---
kind: pipeline
name: default

trigger:
  event:
    - push

steps:
  - name: test-code
    image: python:3.10

    commands:
      - pip install -r requirements.txt -r requirements-dev.txt
      - ./runtests.py
